name: Build Flutter AAB

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'adopt'
        java-version: '17'

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: "3.24.2" 
    
    - name: Install dependencies
      run: flutter pub get

    - name: Flutter Doctor
      run: flutter doctor
    
    - name: Build aab
      run: flutter build appbundle --no-shrink
    
    # Upload do artefato gerado
    - name: Upload appbundle
      uses: actions/upload-artifact@v3
      with:
        name: app-release.aab
        path: build/app/outputs/bundle/release/app-release.aab